### PR TITLE
Add store for redis-go v8

### PR DESCRIPTION
**Pull request by jpcoenen**
A store very similar to the existing `redis-go` store, but since the `redis.UniversalClient` of `redis-go.v8` is incompatible with the client of the previous versions, I'd say it's better to keep the stores separate.

This also contains the changes as proposed in #83. Only commit 30cb82c contains the store.

Unfortunately, this seems to break compatibility with Go 1.12 because of the lack of `errors.Unwrap()`.

### CODE REVIEW

**Comment by Espina2** [comment]
Any way that we can merge this?

Searching in https://endoflife.date/go show that go 1.12 is no longer supported.

**Comment by jpcoenen** [comment]
Rebased both this branch and #83 onto `master`. So they are ready to merge again. 

We're only waiting for approval from @brandur.

**Comment by acastro2** [comment]
Can we get this merged @brandur? It's a really nice approach.

**Comment by fatflowers** [comment]
Any update? Looking forward to this merge😄

**Comment by johansja** [comment]
Anything needed to get this merged? Let me know if there is anything that I can help.

**Comment by Espina2** [comment]
Maybe is time for a fork. This don't look to be maintained anymore

**Comment by jpcoenen** [comment]
> Anything needed to get this merged? Let me know if there is anything that I can help.

Still waiting for approval from @brandur. Afaik, they're the only one with maintainer access to this repo.

> Maybe is time for a fork. This don't look to be maintained anymore

There have actually been 4 releases since this MR was opened. One of them only 2 weeks ago. So it is not necessarily completely unmaintained. But if it is the reason: I am happy to help out with maintaining the project! 

Forking is also an option, but then anyone not reading this conversation would be missing out on updates and we'd miss out on the name of the current repo.

**Comment by brandur** [comment]
Hey @jpcoenen, sorry about the really long delay here. If you're still around to rebase this PR, I'll merge it, make a couple tweaks, and cut a new release. If not, I'll take over the branch and put changes into a new PR.

**Comment by ximyro** [comment]
@brandur Hi! Any progress on merging this pull request?

**Pull request merged**
