### PR TITLE
Do not attempt to use or slice RemoteAddr if its empty

### PR DESCRIPTION
**Pull request by mehcode**
Latest release caused a panic with the handling of `RemoteAdd`.

### CODE REVIEW

**Comment by brandur** [comment]
Thanks @mehcode. I just pushed a change to drop some old versions of Go from the build matrix (it was failing because Golint is now broken for old Go versions). Can you rebase and repush?

**Comment by mehcode** [comment]
Done

**Comment by brandur** [comment]
Thanks again!

**Comment by brandur** [comment]
Released as [2.2.3](https://github.com/throttled/throttled/releases/tag/v2.2.3).

**Pull request merged**
